function [fitresult, gof] = gaussianfit2(x, zvalues)
%CREATEFIT(X,ZVALUES)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: x
%      Y Output: zvalues
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Mar-2025 12:49:33


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, zvalues );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 -Inf 0];
opts.StartPoint = [1 0 1.82162264574033];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
%{
% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'zvalues vs. x', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'zvalues', 'Interpreter', 'none' );
grid on
%}


